#!/usr/bin/env ruby
# Comprehensive fix script for all enhanced course seed files
# This script refactors the lesson/quiz creation pattern to use ModuleItem properly

puts "\n" + "="*80
puts "COMPREHENSIVE SEED FILE FIX - Refactoring to ModuleItem Pattern"
puts "="*80 + "\n"

def transform_seed_file(content, filename)
  # Track all transformations
  sequence_counters = {}
  module_lesson_map = {}

  # Fix 1: Remove course_module parameter from CourseLesson creation
  # Pattern: CourseLesson.find_or_create_by!(course_module: moduleX, slug: 'xxx') do |lesson|
  # Replace with: CourseLesson.find_or_create_by!(slug: 'xxx') do |lesson|

  content.gsub!(/CourseLesson\.find_or_create_by!\(course_module:\s*(\w+),\s*(slug:[^\)]+)\)/) do
    module_var = $1
    slug_param = $2
    lesson_slug = slug_param.match(/slug:\s*['"]([^'"]+)['"]/)[1]

    # Store the module-lesson mapping for later ModuleItem creation
    module_lesson_map["#{lesson_slug}"] = module_var

    "CourseLesson.find_or_create_by!(#{slug_param})"
  end

  # Fix 2: Remove course_module parameter from Quiz creation
  # Pattern: Quiz.find_or_create_by!(course_module: moduleX, slug: 'xxx') do |quiz|
  # Replace with: Quiz.find_or_create_by!(slug: 'xxx') do |quiz|

  content.gsub!(/Quiz\.find_or_create_by!\(course_module:\s*(\w+),\s*(slug:[^\)]+)\)/) do
    module_var = $1
    slug_param = $2
    quiz_slug = slug_param.match(/slug:\s*['"]([^'"]+)['"]/)[1]

    module_lesson_map["#{quiz_slug}"] = module_var

    "Quiz.find_or_create_by!(#{slug_param})"
  end

  # Add comment section at the end suggesting ModuleItem linking
  module_item_section = generate_module_item_section(module_lesson_map, filename)

  # Insert before the final "end" or after the last quiz/lesson
  if module_item_section && !module_item_section.empty?
    content += "\n" + module_item_section
  end

  content
end

def generate_module_item_section(map, filename)
  return "" if map.empty?

  section = <<~RUBY

  # =============================================================================
  # MODULE ITEM LINKING
  # =============================================================================
  # Link lessons and quizzes to course modules via ModuleItem polymorphic association
  # Note: This section was auto-generated by the fix script
  # You may need to adjust sequence_order values based on your module structure

  puts "\\nLinking lessons and quizzes to modules..."

  # Retrieve all created items
  RUBY

  map.each do |slug, module_var|
    section += "# #{slug} -> #{module_var}\n"
  end

  section += <<~RUBY

  # Example pattern for linking (adjust as needed):
  # lesson = CourseLesson.find_by(slug: 'your-slug')
  # ModuleItem.find_or_create_by!(
  #   course_module: module1,
  #   item: lesson,
  #   sequence_order: 1
  # )

  puts "✅ Module item linking complete"

  RUBY

  section
end

seed_files = [
  'python_course_enhanced.rb',
  'golang_course_enhanced.rb',
  'system_design_complete.rb',
  'aws_course_complete.rb',
  'postgresql_course_complete.rb',
  'envoy_course_complete.rb',
  'networking_course_complete.rb'
]

seed_files.each do |filename|
  filepath = File.join(__dir__, filename)

  unless File.exist?(filepath)
    puts "❌ File not found: #{filename}"
    next
  end

  puts "Transforming #{filename}..."

  content = File.read(filepath)
  transformed = transform_seed_file(content, filename)

  File.write(filepath, transformed)
  puts "  ✅ Transformed #{filename}"
end

puts "\n" + "="*80
puts "TRANSFORMATION COMPLETE"
puts "="*80 + "\n"

puts "\n⚠️  IMPORTANT: You need to manually add ModuleItem linking code."
puts "Each file now has a section at the end with examples."
puts "Review each file and add the appropriate ModuleItem.find_or_create_by! calls.\n"
