slug: product-rule-drill
title: Product Rule — Drill
difficulty: medium
sequence_order: 4
estimated_minutes: 2
key_concepts:
- Product Rule
prerequisites: []
content_md: '# Product Rule — Drill 🚀


  ## What is this?

  A concise explanation of the concept.


  ## Key Points


  - Recall the base rule.


  - Substitute symbols carefully.


  - Simplify to standard form.'
exercises:
- type: short_answer
  sequence_order: 2
  require_pass: true
