require 'sidekiq/web'

Rails.application.routes.draw do
  # ----------------------------------------
  # Sidekiq Monitoring
  # ----------------------------------------
  mount Sidekiq::Web => '/sidekiq'

  # ----------------------------------------
  # Root
  # ----------------------------------------
  root to: 'dashboard#show'

  # ----------------------------------------
  # Authentication & Sessions
  # ----------------------------------------
  match '/auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  get '/auth/failure', to: 'sessions#failure'
  get '/logout',                 to: 'sessions#logout', as: :logout
  resources :sessions

  # ----------------------------------------
  # Dashboard
  # ----------------------------------------
  resource :dashboard, only: [:show] # GET /dashboard => dashboard#show
  post   'dashboard/set_status/:id', to: 'dashboard#set_status', as: 'set_status_dashboard'
  get    'page/:page',               to: 'dashboard#show'
  get    'post',                     to: 'dashboard#post'

  # Searching & Services
  post   'questions/tagged',             to: 'dashboard#show_by_order'
  get    '/service/:service',            to: 'dashboard#service'
  get    'search/:tag',                  to: 'dashboard#search'
  get    'comments/:tag',                to: 'dashboard#comments'
  get    'search_service/:service/:port/:tag', to: 'dashboard#search_service'
  get    'service_inlinks/:service',     to: 'dashboard#service_inlinks'

  # ----------------------------------------
  # Challenges
  # ----------------------------------------
  resources :challenges do
    post 'evaluate', on: :member
  end

  # If you don’t need these duplicates (they’re generated by `resources :challenges`), remove them:
  # get '/challenges',        to: 'challenges#index'
  # get '/challenges/new',    to: 'challenges#new'
  # get '/challenges/:id',    to: 'challenges#show'
  get '/challenges/tag/:tag', to: 'challenges#index', as: 'tagged_challenges'

  # ----------------------------------------
  # Problems & Nested Solutions
  # ----------------------------------------
  resources :problems do
    resources :solutions
  end

  # ----------------------------------------
  # Questions (nested under lessons)
  # ----------------------------------------
  resources :questions, only: [] do
    member do
      post :update_status
    end
  end

  # ----------------------------------------
  # Questions
  # ----------------------------------------
  resources :questions

  # Tag & Level Routes
  get 'tags/:tag_name/:site_name(/:sort_by)', to: 'tags#show', as: 'tag'
  get '/level/:id/:site_name',               to: 'dashboard#show_level',  as: 'level_show'
  get '/rlevel/:id/:site_name',              to: 'dashboard#show_rlevel', as: 'rlevel_show'

  # ----------------------------------------
  # Posts
  # ----------------------------------------
  resources :posts do
    collection do
      get 'get_learning_objectives'
    end
  end

  # Additional post routes (mapping to questions controller)
  get '/posts/level/:id',   to: 'questions#level'
  get '/posts/rlevel/:id',  to: 'questions#rlevel'
  get '/posts/sources/:id', to: 'questions#sources'
  get '/posts/sinks/:id',   to: 'questions#sinks'

  # Interest Marking
  post   'posts/:post_id/mark_interested',   to: 'interests#mark_interested',   as: 'mark_interested_post'
  delete 'posts/:post_id/unmark_interested', to: 'interests#unmark_interested', as: 'unmark_interested_post'

  # ----------------------------------------
  # AI (Chat)
  # ----------------------------------------
  get  'ai/chat_form', to: 'ai#chat_form', as: 'ai_chat_form'
  post 'ai/chat',      to: 'ai#chat',      as: 'ai_chat'

  # ----------------------------------------
  # Learning Courses (REDIRECTED to /learn for learning, JSON API still available)
  # ----------------------------------------
  resources :courses, param: :slug, only: [:index, :show] do
    member do
      # Redirect learning actions to /learn
      post :enroll, to: redirect('/learn')
      get :continue, to: redirect('/learn')
      get :start, to: redirect('/learn')
    end
    
    resources :course_modules, path: 'modules', param: :slug, only: [:show], as: :modules

    # Remediation now handled by continuous learning
    resource :remediation_session, only: [:show], controller: 'remediation_sessions' do
      post :complete_item
      post :skip
    end
  end
  
  # ----------------------------------------
  # Learning Routes - All content served via React app on port 5002
  # API endpoints below provide data to the React frontend
  # ----------------------------------------
  
  # Keep OLD routes commented for reference (DO NOT USE)
  # # Interactive Learning Units (DEPRECATED - redirects to /learn)
  # get 'interactive_learning', to: 'interactive_learning#index', as: :interactive_learning_index
  # get 'interactive_learning/dashboard', to: 'interactive_learning#dashboard', as: :interactive_learning_dashboard
  # scope '/interactive_learning', as: :interactive_learning do
  #   get ':slug', to: 'interactive_learning#show', as: ''
  #   post ':slug/start', to: 'interactive_learning#start', as: '_start'
  #   post ':slug/complete_explanation', to: 'interactive_learning#complete_explanation', as: '_complete_explanation'
  #   post ':slug/submit_practice', to: 'interactive_learning#submit_practice', as: '_submit_practice'
  #   post ':slug/submit_quiz', to: 'interactive_learning#submit_quiz', as: '_submit_quiz'
  #   post ':slug/complete_scenario', to: 'interactive_learning#complete_scenario', as: '_complete_scenario'
  #   get ':slug/hint', to: 'interactive_learning#get_hint', as: '_hint'
  # end
  
  # # Guided Learning Flow (DEPRECATED - redirects to /learn)
  # get 'start_learning', to: 'guided_learning#start', as: :start_learning
  # get 'guided_learning/progress', to: 'guided_learning#progress', as: :guided_learning_progress
  # post 'guided_learning/reset', to: 'guided_learning#reset', as: :reset_learning_progress

  # Reviews (spaced repetition)
  get 'reviews', to: 'reviews#show', as: :reviews
  
  # Lessons (using CourseLesson)
  resources :lessons, only: [:show], controller: 'course_lessons' do
    member do
      post :complete
    end
  end
  
  # Quizzes
  resources :quizzes, only: [:show] do
    collection do
      get :practice
      post :generate_review_session
      post :generate_topic_deepdive
      post :generate_mastery_challenge
    end
    member do
      post :start
      post :submit
      get :result
      post :validate_answer
      post :adaptive_retry
    end
  end
  
  # Remediation routes
  namespace :remediation do
    post :track_lesson_review
    get 'mini_lesson/:question_id', action: :mini_lesson, as: :mini_lesson
    get :recommendations
    get :stats
    get :effectiveness
  end
  
  # Hands-On Labs
  resources :hands_on_labs, only: [:index, :show] do
    member do
      post :start
      get :lab_session
      post :validate_step
      post :request_hint
      post :pause
      post :resume
      post :complete
      get :result
    end
  end
  
  # Adaptive Practice
  scope :adaptive_practice, controller: :adaptive_practice do
    get  '/',          action: :start,         as: :start_adaptive_practice
    get  '/question',  action: :next_question, as: :next_adaptive_question
    post '/answer',    action: :submit_answer, as: :submit_adaptive_answer
    get  '/complete',  action: :complete,      as: :adaptive_practice_complete
  end
  
  # Analytics
  resources :analytics, only: [] do
    collection do
      get :dashboard
      get :skill_radar_data
      get :progress_timeline_data
      get :weakness_analysis
    end
  end
  
  # Diagnostic Quiz
  resource :diagnostic_quiz, only: [] do
    get :start
    post :answer
    get :evaluate
  end
  
  # Study Plans
  resources :study_plans do
    member do
      patch :pause
      patch :resume
    end
  end
  
  # Exam Simulations
  resources :exam_simulations, only: [:index, :show] do
    collection do
      get ':certification_type/start', action: :start, as: :start
      post ':certification_type/begin', action: :begin_exam, as: :begin
    end
    member do
      post :submit
      get :result
      get :review
    end
  end
  
  # Reviews (Spaced Repetition)
  resources :reviews, only: [:index] do
    collection do
      get :practice
      get :stats
    end
    member do
      post :submit
    end
  end
  
  # Achievements
  resources :achievements, only: [:index] do
    collection do
      post :check
    end
  end
  
  # User Profile Stats
  get 'profile/stats', to: 'profiles#stats', as: 'profile_stats'

  # ----------------------------------------
  # Learning Paths
  # ----------------------------------------
  resources :learning_paths, only: [:index]
  # ----------------------------------------
  # ActionCable WebSocket endpoint
  # ----------------------------------------
  mount ActionCable.server => '/cable'

  # ----------------------------------------
  # Mastery Decay Dashboard
  # ----------------------------------------
  namespace :mastery do
    get 'decay', to: 'decay#index'
  end

  # ----------------------------------------
  # Course Shortcuts (Frontend)
  # ----------------------------------------
  get '/docker', to: 'courses#show', defaults: { slug: 'docker-fundamentals' }
  get '/docker-bootcamp', to: 'courses#show', defaults: { slug: 'docker-containers-bootcamp' }
  get '/kubernetes', to: 'courses#show', defaults: { slug: 'kubernetes-complete-guide' }

  # ----------------------------------------
  # Docker/K8s Learning Platform API
  # ----------------------------------------
  namespace :api do
    # Mastery & Decay Visualization API
    namespace :mastery do
      get 'decay_visualization', to: 'mastery#decay_visualization'
      post 'request_stealth_review', to: 'mastery#request_stealth_review'
      get 'stealth_reviews', to: 'mastery#stealth_reviews'
      get 'decay_analysis/:canonical_command', to: 'mastery#decay_analysis'
      get 'commands_at_risk', to: 'mastery#commands_at_risk'
      post 'apply_decay_batch', to: 'mastery#apply_decay_batch'
      post 'track_attempt', to: 'mastery#track_attempt'
      get 'lesson_reviews', to: 'mastery#lesson_reviews'
      post 'complete_review', to: 'mastery#complete_review'
      get 'check_gate', to: 'mastery#check_gate'
      post 'generate_drill_session', to: 'mastery#generate_drill_session'
      post 'complete_drill', to: 'mastery#complete_drill'
      post 'pass_gate', to: 'mastery#pass_gate'
    end
    namespace :v1 do
      # Microlesson Runner API (Option A)
      get  'microlessons/by_module', to: 'microlessons#by_module'
      get  'microlessons/:id',       to: 'microlessons#show'
      post 'exercises/:id/attempt',  to: 'exercise_attempts#create'
      
      # Track-based Courses API (e.g., /api/v1/kubernetes/courses)
      get ':track/courses', to: 'courses#index_by_track'
      get ':track/courses/:slug', to: 'courses#show_by_track'
      get ':track/courses/:course_slug/modules', to: 'courses#modules_by_track'
      get ':track/courses/:course_slug/modules/:module_slug', to: 'courses#module_by_track'
      get ':track/labs', to: 'labs#index_by_track'
      get ':track/labs/:id', to: 'labs#show_by_track'
      
      # Generic Courses API (published courses across all tracks)
      get    'courses',                                    to: 'courses#index'
      get    'courses/:slug',                              to: 'courses#show'
      get    'courses/:slug/modules',                      to: 'courses#modules'

      # User progress tracking (requires authentication)
      post   'courses/:slug/enroll',                       to: 'courses#enroll'
      get    'courses/:slug/progress',                     to: 'courses#progress'
      post   'courses/:slug/lessons/:lesson_slug/complete', to: 'courses#complete_lesson'

      # NEW: Enhanced progress tracking with review/resume functionality
      post   'courses/:slug/track_access',                 to: 'courses#track_access'
      get    'courses/:slug/resume_point',                 to: 'courses#resume_point'
      post   'courses/:slug/review_session',               to: 'courses#review_session'

      # Course Import API (for bulk course uploads)
      post   'course_imports', to: 'course_imports#create'

      # React Learning Interface API (using continuous_learning controller)
      get    'learning/session',          to: '/continuous_learning#api_session'
      get    'learning/modules',          to: '/continuous_learning#api_modules'
      post   'learning/command',          to: '/continuous_learning#api_validate_command'
      post   'learning/complete/command', to: '/continuous_learning#api_complete_command'
      post   'learning/complete/lesson',  to: '/continuous_learning#api_complete_lesson'
      post   'learning/complete/task',    to: '/continuous_learning#api_complete_task'
      get    'learning/mastery',          to: '/continuous_learning#api_mastery_scores'

      # Linux Courses API
      namespace :linux do
        get    'courses',                    to: 'linux_courses#index'
        get    'courses/:id',                to: 'linux_courses#show'
        get    'courses/:course_id/modules', to: 'linux_courses#modules'
        get    'courses/:course_id/modules/:id', to: 'linux_courses#module_show'
        get    'labs',                       to: 'linux_courses#labs'
        get    'labs/:id',                   to: 'linux_courses#lab_show'
        match  '*all',                       to: 'linux_courses#cors_preflight', via: :options
      end


      # Docker Courses API
      namespace :docker do
        get    'courses',                    to: 'docker_courses#index'
        get    'courses/:id',                to: 'docker_courses#show'
        get    'courses/:course_id/modules', to: 'docker_courses#modules'
        get    'courses/:course_id/modules/:id', to: 'docker_courses#module_show'
        get    'courses/:course_id/modules/:id/progressive', to: 'docker_courses#progressive'
        get    'commands',                   to: 'docker_courses#commands'
        get    'labs',                       to: 'docker_courses#labs'
        get    'labs/:id',                   to: 'docker_courses#lab_show'
        post   'execute',                    to: 'docker_courses#execute_command'
        match  '*all',                       to: 'docker_courses#cors_preflight', via: :options
      end

      # System Design Courses API
      namespace :system_design do
        get    'courses',                    to: 'system_design_courses#index'
        get    'courses/:id',                to: 'system_design_courses#show'
        get    'courses/:course_id/modules', to: 'system_design_courses#modules'
        get    'courses/:course_id/modules/:id', to: 'system_design_courses#module_show'
        get    'labs',                       to: 'system_design_courses#labs'
        get    'labs/:id',                   to: 'system_design_courses#lab_show'
        match  '*all',                       to: 'system_design_courses#cors_preflight', via: :options
      end

      # Coding Interview Courses API
      namespace :coding do
        get    'courses',                    to: 'coding_courses#index'
        get    'courses/:id',                to: 'coding_courses#show'
        get    'courses/:course_id/modules', to: 'coding_courses#modules'
        get    'courses/:course_id/modules/:id', to: 'coding_courses#module_show'
        match  '*all',                       to: 'coding_courses#cors_preflight', via: :options
      end

      # ----------------------------------------
      # Progressive Flow System API Routes
      # ----------------------------------------
      # Learning Tracks
      resources :progressive_tracks, only: [:index, :show], controller: 'progressive_challenges', path: 'progressive/tracks' do
        member do
          get :challenges
        end
      end

      # Challenges
      resources :progressive_challenges, only: [:index, :show], path: 'progressive/challenges' do
        member do
          get :unlock_status, action: :check_unlock
          post 'levels/:level_number/complete', action: :complete_level
          get :progress
        end
      end

      # User Progress & Stats
      scope 'progressive/user', controller: 'progressive_users' do
        get :progress
        get :stats
        get :level
        get :streak
        post :award_xp
        get :rank
        
        # Achievements
        get 'achievements', action: :achievements
        get 'achievements/unlocked', action: :achievements_unlocked
        
        # Skills
        get 'skills', action: :skills
        get 'skills/tree', action: :skill_tree
        get 'skills/top', action: :top_skills
        
        # Assessment
        post 'assessment/save', action: :save_assessment
      end

      # Leaderboards
      scope 'progressive/leaderboard', controller: 'progressive_leaderboards' do
        get 'global', action: :global
        get 'friends', action: :friends
        get 'challenge/:challenge_id', action: :challenge
      end

      # Achievements (separate from user achievements)
      resources :progressive_achievements, only: [:index], path: 'progressive/achievements' do
        collection do
          get :unlocked
          post :check
        end
      end

      # Daily Challenges
      resources :progressive_daily_challenges, only: [:index], path: 'progressive/daily-challenges' do
        collection do
          get :history
        end
        member do
          post :complete
        end
      end

      # Notifications
      resources :progressive_notifications, only: [:index], path: 'progressive/notifications' do
        collection do
          get :unread
          post :mark_all_read
        end
        member do
          post :mark_read
        end
      end


      # Docker Learning endpoints
      get    'docker_learning/next_command',     to: 'docker_learning#next_command'
      post   'docker_learning/submit_practice',  to: 'docker_learning#submit_practice'
      get    'docker_learning/stats',            to: 'docker_learning#stats'
      get    'docker_learning/recommendations',  to: 'docker_learning#recommendations'
      get    'docker_learning/commands',         to: 'docker_learning#commands'
      get    'docker_learning/commands/:id',     to: 'docker_learning#command'
      get    'docker_learning/review_due',       to: 'docker_learning#review_due'
      
      # Labs endpoints (terminal-based)
      get    'labs',                             to: 'labs#index'
      get    'labs/:id',                         to: 'labs#show'
      post   'labs/:id/start',                   to: 'labs#start'
      get    'labs/sessions/:id',                to: 'labs#session_status'
      post   'labs/sessions/:id/validate_step',  to: 'labs#validate_step'
      post   'labs/sessions/:id/request_hint',   to: 'labs#request_hint'
      post   'labs/sessions/:id/pause',          to: 'labs#pause'
      post   'labs/sessions/:id/resume',         to: 'labs#resume'
      post   'labs/sessions/:id/complete',       to: 'labs#complete'
      delete 'labs/sessions/:id',                to: 'labs#destroy_session'
      get    'labs/sessions',                    to: 'labs#sessions'

      # Code Labs endpoints (code editor-based)
      get    'code_labs',                        to: 'code_labs#index'
      get    'code_labs/:id',                    to: 'code_labs#show'
      post   'code_labs/:id/execute',            to: 'code_labs#execute'
      post   'code_labs/:id/validate',           to: 'code_labs#validate'
      post   'code_labs/:id/submit',             to: 'code_labs#submit'
      get    'code_labs/:id/hint',               to: 'code_labs#hint'
      get    'code_labs/:id/solution',           to: 'code_labs#solution'
      
      # SQL Labs endpoints (SQL query editor-based)
      resources :sql_labs, only: [] do
        member do
          post :execute
          post :validate
          post :submit
        end
      end

      # Course Adaptations API (struggle tracking and course improvements)
      get    'course_adaptations',                       to: 'course_adaptations#index'
      get    'course_adaptations/summary',               to: 'course_adaptations#summary'
      get    'course_adaptations/pending_count',         to: 'course_adaptations#pending_count'
      get    'course_adaptations/lab/:lab_id/analysis',  to: 'course_adaptations#lab_analysis'
      get    'course_adaptations/module/:module_id/analysis', to: 'course_adaptations#module_analysis'
      post   'course_adaptations/auto_suggest',          to: 'course_adaptations#auto_suggest'
      get    'course_adaptations/:id',                   to: 'course_adaptations#show'
      post   'course_adaptations/:id/approve',           to: 'course_adaptations#approve'
      post   'course_adaptations/:id/dismiss',           to: 'course_adaptations#dismiss'
      post   'course_adaptations/:id/implement',         to: 'course_adaptations#implement'

      # Kubernetes Learning endpoints
      get    'kubernetes/modules',              to: 'kubernetes_content#modules'
      get    'kubernetes/lessons/:id',          to: 'kubernetes_content#lesson'
      post   'kubernetes/lessons/:id/complete', to: 'kubernetes_content#complete_lesson'
      get    'kubernetes/progress',             to: 'kubernetes_content#progress'
      get    'kubernetes/labs',                 to: 'kubernetes_content#labs'

      # ----------------------------------------
      # UPSC CSE Preparation Platform API
      # ----------------------------------------
      namespace :upsc do
        # Dashboard & Analytics
        get 'dashboard',           to: 'dashboard#index'
        get 'dashboard/overview',  to: 'dashboard#overview'
        get 'dashboard/progress',  to: 'dashboard#progress'
        get 'dashboard/analytics', to: 'dashboard#analytics'

        # Subjects
        resources :subjects do
          collection do
            get :prelims
            get :mains
            get :optional
          end
        end

        # Topics
        resources :topics do
          member do
            post :start_learning, to: 'topics#start_learning'
            post :complete, to: 'topics#mark_complete'
          end
          collection do
            get :high_yield
          end
        end

        # Questions
        resources :questions do
          member do
            post :verify_answer
          end
          collection do
            get :random
          end
        end

        # Tests
        resources :tests do
          member do
            post :start
          end
          collection do
            get :my_attempts
          end
        end

        # Test Attempts
        post 'tests/attempts/:attempt_id/submit_answer', to: 'tests#submit_answer'
        post 'tests/attempts/:attempt_id/submit', to: 'tests#submit'
        get 'tests/attempts/:attempt_id/results', to: 'tests#results'

        # Writing Questions
        resources :writing_questions do
          collection do
            get :daily
          end
        end

        # User Answers (Answer Writing)
        resources :user_answers do
          member do
            post :request_evaluation
          end
          collection do
            get :statistics
          end
        end

        # News Articles (Current Affairs)
        resources :news_articles do
          collection do
            get :today
            get :this_week
            get :important
            get :categories
          end
        end

        # Study Plans
        resources :study_plans do
          member do
            post :activate
          end
          collection do
            get :active
            post :generate
          end
        end

        # Daily Tasks
        resources :daily_tasks do
          member do
            post :complete
          end
          collection do
            get :today
            get :week
            post :bulk_create
            get :statistics
          end
        end

        # Revisions (Spaced Repetition)
        resources :revisions do
          member do
            post :complete, to: 'revisions#mark_completed'
          end
          collection do
            get :today
            get :upcoming
            post :schedule_topic
            get :statistics
          end
        end

        # AI Features (Ollama Integration)
        get 'ai/status', to: 'ai#status'
        post 'ai/explain', to: 'ai#explain'
        post 'ai/generate_questions', to: 'ai#generate_questions'
        post 'ai/study_plan_suggestions', to: 'ai#study_plan_suggestions'

        # CORS preflight for all UPSC routes
        match '*all', to: 'base#cors_preflight', via: :options
      end
    end
  end

  get 'learning_path/:tag', to: 'learning_paths#show', as: 'learning_path'
  
  # Catch-all: redirect everything else to dashboard to enforce minimal surface
  match '*unmatched', to: redirect('/'), via: :all
end
